language: python

python:
- '2.7'

env:
  global:
  - secure: GIZt8Nas050nsHHeje1s7P3bSpVJlBtz2SRQZPqFd6rqOLpkkJ6LVlFLCoUJXMdkshX3ZdrPcqtyg3tvI/2dnAC/fACTEIMysBgMOW4LVt/+se05hmGDbsSPgJHkOzvDz6G2csMBLWDHdEQvGGNWn9rVHY3UhWnhDX6L33mbK14=
  - secure: p2Q/X4bQII4cQV71XKF5OBhvvIBDAmI4BFl+3has/z2R8bOTBm1b5vEIem4/hRTRJ9ZP2VHo/IpGgy8mpBF7oiVdMuW6cj0lLJIE5Pm6l89oCPg3ZknGV03WUbkZhs48XZ1f44boUaZ1HZYR57wCfHpj7EzSn1I2BwgCjGUdZNg=
  - secure: rFo920MeLZb/F4xpOQFQfnjIccMhxMroxMO266z5aYzp7sDRXtGd57uPX6xsCfnupYEQdLz0x4yphxzM+Icm3vdbAu4KjxA2/Js/FHfhGlHaOUGyTkSkp3POMDxVY05JwfGI+7kJCGAbsBTisgZi8OXXfLxIsn4HQ94gmSESEu0=
  matrix:
  - SELENIUM_PLATFORM="OS X 10.6"
    SELENIUM_BROWSER="firefox"
    SELENIUM_VERSION="27"
  - SELENIUM_PLATFORM="Windows 8"
    SELENIUM_BROWSER="firefox"
    SELENIUM_VERSION="27"
  - SELENIUM_PLATFORM="Windows 7"
    SELENIUM_BROWSER="firefox"
    SELENIUM_VERSION="27"

install:
- pip install Django==1.6.2
- pip install django-pjaxr==1.0.1
- pip install selenium==2.40.0
- npm install
- npm run-script prepare-tests
- cd test_app
- npm install
- npm run-script bower-install
- cd ..

addons:
  sauce_connect: true

script:
- python test_app/tests/runtests.py

notifications:
  email: false
