language: python
python:
  - 2.7

install: pip install flask==0.10.1

before_script:
  - "export DISPLAY=:99.0"  # http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3  # give xvfb some time to start
  - python ./tests/app.py 2>/dev/null &

script: phantomjs ./tests/run-qunit.js "http://localhost:8000/"

notifications:
  email: false
